image: registry.gitlab.com/flyingarmageddon/webifier

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - python /app/run.py "$(pwd)/web" prebuild
    - mkdir build
    - cp -r prebuild/assets build/assets
    - cp prebuild/*.* build/.
    - rm build/sw.js
  artifacts:
    paths:
      - build/
    expire_in: 1 week

deploy to test:
  stage: deploy
  variables:
    WEB_SUBDOMAIN: testplan
    WEB_DOMAIN: flyingarmageddon.pl
  script:
    - bash /app/check.sh
    - cp "$ANSIBLE_SSH_PRIV" /etc/ansible/id_rsa
    - chmod 400 /etc/ansible/id_rsa

    - export WEB_SRC_FILES="$(pwd)/build/"
    - ansible-playbook /app/ansible/install.yml

    - echo "Your website should be available at $WEB_SUBDOMAIN.$WEB_DOMAIN"


deploy to prod:
  stage: deploy
  when: manual
  image: mwienk/docker-lftp:latest
  variables:
    SRC_PATH: build
    TARGET_PATH: zseilplan
  script: 
    - lftp -e "set ftp:ssl-allow false; mirror -Rnv \"$SRC_PATH\" \"$TARGET_PATH\"; exit;" -u $PROD_FTP_USERNAME,$PROD_FTP_PASSWORD $PROD_FTP_HOST
  # only:
  #   - master