Deploy to development:
  script:
  - apt update -qq
  - apt install -y --force-yes -qq git
  - app_dir=$(pwd)
  - cd /tmp
  - git clone http://git.int.polgesek.pl/jpolgesek/superdeploytool.git
  - cd superdeploytool
  - python -m pip install -r req.txt
  - python deploy.py _ _ --path $app_dir --dev --http-rootdir-app=/ --http-rootdir-manifest=/ --hostname=testplan.polgesek.pl --uploader=ftp --username=$testplan_polgesek_pl_ftp_user --password=$testplan_polgesek_pl_ftp_pass --uploader-rootdir-manifest=/ --uploader-rootdir-app=/

Deploy to production:
  when: manual
  script:
  - apt update -qq
  - apt install -y --force-yes -qq git
  - app_dir=$(pwd)
  - cd /tmp
  - git clone http://git.int.polgesek.pl/jpolgesek/superdeploytool.git
  - cd superdeploytool
  - python -m pip install -r req.txt
  - python deploy.py _ _ --path $app_dir --dev --http-rootdir-app=/zseilplan/ --http-rootdir-manifest=/zseilplan/ --hostname=dev.polgesek.pl --uploader=ftp --username=$zseilplan_dev_polgesek_pl_ftp_user --password=$zseilplan_dev_polgesek_pl_ftp_pass --uploader-rootdir-manifest=/zseilplan/ --uploader-rootdir-app=/zseilplan/

Deploy to plan.zseil.pl:
  when: manual
  script:
  - cd _do_not_upload
  - cd deployment_tool
  - pip install -r req.txt
  - python deploy.py plan.zseil.pl