image: python:3.7.7-buster

Deploy to development:
  script:
  - apt update -qq
  - apt install -y --force-yes -qq git
  - app_dir=$(pwd)
  - cd /tmp
  - git clone https://gitlab.com/jpolgesek/superdeploytool
  - cd superdeploytool
  - python3 -m pip install -r req.txt
  - python3 deploy.py _ _ --path $app_dir --dev --http-rootdir-app=/ --http-rootdir-manifest=/ --hostname=testplan.polgesek.pl --uploader=ftp --username=$testplan_polgesek_pl_ftp_user --password=$testplan_polgesek_pl_ftp_pass --uploader-rootdir-manifest=/ --uploader-rootdir-app=/

Deploy to production:
  when: manual
  script:
  - apt update -qq
  - apt install -y --force-yes -qq git
  - app_dir=$(pwd)
  - cd /tmp
  - git clone https://gitlab.com/jpolgesek/superdeploytool
  - cd superdeploytool
  - python3 -m pip install -r req.txt
  - python3 deploy.py _ _ --path $app_dir --http-rootdir-app=/zseilplan/ --http-rootdir-manifest=/zseilplan/ --hostname=dev.polgesek.pl --uploader=ftp --username=$zseilplan_dev_polgesek_pl_ftp_user --password=$zseilplan_dev_polgesek_pl_ftp_pass --uploader-rootdir-manifest=/ --uploader-rootdir-app=/zseilplan/

Deploy to plan.zseil.pl (staging):
  when: manual
  script:
  - apt update -qq
  - apt install -y --force-yes -qq git
  - app_dir=$(pwd)
  - cd /tmp
  - git clone https://gitlab.com/jpolgesek/superdeploytool
  - cd superdeploytool
  - python3 -m pip install -r req.txt
  - python3 deploy.py _ _ --path $app_dir --http-rootdir-app=/ --http-rootdir-manifest=/ --hostname=plan.zseil.pl --uploader=scp --username=$plan_zseil_pl_scp_user --password=$plan_zseil_pl_scp_pass --uploader-rootdir-manifest=/var/www/zseil/plan/ --uploader-rootdir-app=/var/www/zseil/plan/
